/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenNotificationsRouteImport } from './routes/kitchen-notifications'
import { Route as KitchenHistoryRouteImport } from './routes/kitchen-history'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminSlotsRouteImport } from './routes/admin-slots'
import { Route as AdminOrdersRouteImport } from './routes/admin-orders'
import { Route as AdminMenuRouteImport } from './routes/admin-menu'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenNotificationsRoute = KitchenNotificationsRouteImport.update({
  id: '/kitchen-notifications',
  path: '/kitchen-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenHistoryRoute = KitchenHistoryRouteImport.update({
  id: '/kitchen-history',
  path: '/kitchen-history',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin-slots',
  path: '/admin-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin-orders',
  path: '/admin-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin-menu',
  path: '/admin-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-menu': typeof AdminMenuRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-slots': typeof AdminSlotsRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-history': typeof KitchenHistoryRoute
  '/kitchen-notifications': typeof KitchenNotificationsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-menu': typeof AdminMenuRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-slots': typeof AdminSlotsRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-history': typeof KitchenHistoryRoute
  '/kitchen-notifications': typeof KitchenNotificationsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-menu': typeof AdminMenuRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-slots': typeof AdminSlotsRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-history': typeof KitchenHistoryRoute
  '/kitchen-notifications': typeof KitchenNotificationsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-menu'
    | '/admin-orders'
    | '/admin-slots'
    | '/dashboard'
    | '/kitchen'
    | '/kitchen-history'
    | '/kitchen-notifications'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-menu'
    | '/admin-orders'
    | '/admin-slots'
    | '/dashboard'
    | '/kitchen'
    | '/kitchen-history'
    | '/kitchen-notifications'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-menu'
    | '/admin-orders'
    | '/admin-slots'
    | '/dashboard'
    | '/kitchen'
    | '/kitchen-history'
    | '/kitchen-notifications'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  DashboardRoute: typeof DashboardRoute
  KitchenRoute: typeof KitchenRoute
  KitchenHistoryRoute: typeof KitchenHistoryRoute
  KitchenNotificationsRoute: typeof KitchenNotificationsRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-notifications': {
      id: '/kitchen-notifications'
      path: '/kitchen-notifications'
      fullPath: '/kitchen-notifications'
      preLoaderRoute: typeof KitchenNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-history': {
      id: '/kitchen-history'
      path: '/kitchen-history'
      fullPath: '/kitchen-history'
      preLoaderRoute: typeof KitchenHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-slots': {
      id: '/admin-slots'
      path: '/admin-slots'
      fullPath: '/admin-slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-orders': {
      id: '/admin-orders'
      path: '/admin-orders'
      fullPath: '/admin-orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-menu': {
      id: '/admin-menu'
      path: '/admin-menu'
      fullPath: '/admin-menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  DashboardRoute: DashboardRoute,
  KitchenRoute: KitchenRoute,
  KitchenHistoryRoute: KitchenHistoryRoute,
  KitchenNotificationsRoute: KitchenNotificationsRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
